[package]
name = "logtime"
version = "0.1.0"
authors = ["Jeremy List <jeremy.list@youdo.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
